devices:
  - name: "devices_01"
    ip: "10.0.1.1"
    status: "up"
    # community_string: "public_lab_snmp" # For when you implement SNMP
  - name: "devices_02"
    ip: "10.0.0.1"
    status: "up"
    # community_string: "public_lab_snmp"
  - name: "device_03"
    ip: "192.168.254.254"
    status: "down" 
    # To test error handling