devices:
  R1:
    connections:
      cli:
        ip: 10.10.20.171
        protocol: ssh
    credentials:
      default:
        password: cisco
        username: cisco
      enable:
        password: cisco
    os: iol
    type: iol
  R2:
    connections:
      cli:
        ip: 10.10.20.172
        protocol: ssh
    credentials:
      default:
        password: cisco
        username: cisco
      enable:
        password: cisco
    os: iol
    type: iol
  SW1:
    connections:
      cli:
        ip: 10.10.20.173
        protocol: ssh
    credentials:
      default:
        password: cisco
        username: cisco
      enable:
        password: cisco
    os: iol
    type: iol
  SW2:
    connections:
      cli:
        ip: 10.10.20.174
        protocol: ssh
    credentials:
      default:
        password: cisco
        username: cisco
      enable:
        password: cisco
    os: iol
    type: iol
